title: Mary Marketing V2
baseURL: /
params:
  layout_type: full-width
  style: minimal
  palette: blue
  mode: light
  base_font: serif
  header:
    type: header
    template: header
    title: Mary-Marketing
    logo_alt: Logo Mary Marketing
    has_primary_nav: true
    primary_nav_links:
      - type: action
        template: action
        label: Rédaction web
        url: /redaction-web/
        style: primary
        no_follow: false
      - type: action
        template: action
        label: Tarifs
        url: /tarifs/
        style: primary
        no_follow: false
      - type: action
        template: action
        label: À propos
        url: /a-propos/
        style: primary
        no_follow: false
      - type: action
        template: action
        label: Blog
        url: /blog
        style: primary
        no_follow: false
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        template: action
        label: Contactez-moi
        url: /contact
        style: secondary
        no_follow: false
    has_anncmnt: true
    anncmnt_content: >
      En poursuivant votre navigation vous acceptez l'utilisation, de la part de
      Mary-Marketing, de **cookies** et autres tracker dans l'objectif de
      mesurer l'audience, de mieux comprendre votre expérience utilisateur et de
      vous proposer les offres et services adaptés à votre profil. Pour en
      savoir plus, [**cliquez ici**](/politique-confidentialite).
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: Banner Cookies
    logo: images/logo-header-mary-marketing.jpg
  footer:
    type: footer
    template: footer
    logo: images/logo-footer-mary-marketing.jpeg
    logo_alt: logo footer Mary Marketing
    has_primary_nav: true
    primary_nav_title: Entreprise
    primary_nav_links:
      - type: action
        template: action
        label: À propos
        url: /a-propos/
        style: link
      - label: Mentions légales
        url: /mentions-legales/
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        no_follow: true
        type: action
      - label: Politique de confidentialité
        url: /politique-de-confidentialite/
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        no_follow: true
        type: action
    has_secondary_nav: true
    secondary_nav_title: Blog
    secondary_nav_links:
      - type: action
        template: action
        label: Tout les articles
        url: /blog/
        style: link
      - type: action
        template: action
        label: Actualité marketing
        url: /blog/categorie/actualite-marketing-digital/
        style: link
      - type: action
        template: action
        url: /blog/categorie/referencement-naturel-seo/
        style: link
        label: Référencement naturel
        no_follow: false
    has_tertiary_nav: true
    tertiary_nav_title: Newsletter
    tertiary_nav_links:
      - type: action
        template: action
        label: S'inscrire
        style: secondary
        no_follow: true
        icon: arrow-right
        has_icon: true
        url: '#newsletter'
    has_social: true
    social_links:
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/company/mary-marketing'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: YouTube
        url: 'https://www.facebook.com/marymarketing.pro'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
    content: |-
      2021
       &copy; Mary-Marketing rédactrice web freelance. Tous les droits 
      réservés. Ne pas utiliser le contenus et les photos sans autorisations.
  domain: 'https://diligent-pluto-bbfe2.netlify.app'
  favicon: /images/logo-favicon-mary-marketing.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
