title: Mary Marketing V2
baseURL: /
params:
  layout_type: full-width
  style: minimal
  palette: blue
  mode: light
  base_font: serif
  header:
    type: header
    template: header
    title: Mary-Marketing
    logo: /images/logo-header.png
    logo_alt: Logo Mary Marketing
    has_primary_nav: true
    primary_nav_links:
      - type: action
        template: action
        label: Rédaction web
        url: /redaction-web
        style: primary
      - type: action
        template: action
        label: Tarifs
        url: /tarifs
        style: primary
      - type: action
        template: action
        label: À propos
        url: /a-propos
        style: primary
      - type: action
        template: action
        label: Blog
        url: /blog
        style: primary
    has_secondary_nav: true
    secondary_nav_links:
      - type: action
        template: action
        label: Contactez-moi
        url: /contact
        style: secondary
    has_anncmnt: true
    anncmnt_content: >
      En poursuivant votre navigation vous acceptez l'utilisation, de la part de
      Mary-Marketing, de cookies et autres tracker dans l'objectif de mesurer
      l'audience, de mieux comprendre votre expérience utilisateur et de vous
      proposer les offres et services adaptés à votre profil. Pour gérer et
      modifier vos paramètres, [**Cliquez ici**](/politique-confidentialité).
    anncmnt_align: left
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: Banner Cookies
  footer:
    type: footer
    template: footer
    logo: /images/logo-footer.png
    logo_alt: DIY logo
    has_primary_nav: true
    primary_nav_title: Entreprise
    primary_nav_links:
      - type: action
        template: action
        label: À propos
        url: /a-propos
        style: link
    has_secondary_nav: true
    secondary_nav_title: Blog
    secondary_nav_links:
      - type: action
        template: action
        label: News
        url: /blog/category/news
        style: link
      - type: action
        template: action
        label: General
        url: /blog/category/general
        style: link
      - type: action
        template: action
        label: Tutorials
        url: /blog/category/tutorials
        style: link
    has_tertiary_nav: true
    tertiary_nav_title: Liens utiles
    tertiary_nav_links:
      - type: action
        template: action
        label: Mentions légales
        url: /mentions-legales
        style: link
        no_follow: true
      - type: action
        template: action
        label: "Politique de\_ confidentialité"
        url: /politique-de-confidentialite
        style: link
    has_social: true
    social_links:
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
      - type: action
        template: action
        label: YouTube
        url: 'https://www.facebook.com/'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
    content: |-
      2021
       &copy; Mary-Marketing rédactrice web freelance. Tous les droits 
      réservés. Ne pas utiliser le contenus et les photos sans autorisations.
  domain: 'https://diligent-pluto-bbfe2.netlify.app'
  favicon: /images/logo-favicon-mary-marketing.png
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
